import React, { useState } from "react";
import {
  View,
  Text,
  FlatList,
  StyleSheet,
  TouchableOpacity,
} from "react-native";
import CompeticaoCardComponent from "./CompeticaoCardComponent";
import Flag from "react-native-flags";

const countryNames = {
  Afghanistan: "Afeganistão",
  Albania: "Albânia",
  Algeria: "Argélia",
  Andorra: "Andorra",
  Angola: "Angola",
  "Antigua-and-Barbuda": "Antígua e Barbuda",
  Argentina: "Argentina",
  Armenia: "Armênia",
  Australia: "Austrália",
  Austria: "Áustria",
  Azerbaijan: "Azerbaijão",
  Bahamas: "Bahamas",
  Bahrain: "Bahrein",
  Bangladesh: "Bangladesh",
  Barbados: "Barbados",
  Belarus: "Bielorrússia",
  Belgium: "Bélgica",
  Belize: "Belize",
  Benin: "Benin",
  Bhutan: "Butão",
  Bolivia: "Bolívia",
  "Bosnia-and-Herzegovina": "Bósnia e Herzegovina",
  Botswana: "Botswana",
  Brazil: "Brasil",
  Brunei: "Brunei",
  Bulgaria: "Bulgária",
  Burkina_Faso: "Burquina Faso",
  Burundi: "Burundi",
  "Cabo-Verde": "Cabo Verde",
  Cambodia: "Camboja",
  Cameroon: "Camarões",
  Canada: "Canadá",
  "Central-African-Republic": "República Centro-Africana",
  Chad: "Chade",
  Chile: "Chile",
  China: "China",
  Colombia: "Colômbia",
  Comoros: "Comores",
  Congo: "Congo",
  "Costa-Rica": "Costa Rica",
  Croatia: "Croácia",
  Cuba: "Cuba",
  Cyprus: "Chipre",
  "Czech-Republic": "República Tcheca",
  Denmark: "Dinamarca",
  Djibouti: "Djibuti",
  Dominica: "Dominica",
  "Dominican-Republic": "República Dominicana",
  "East-Timor": "Timor-Leste",
  Ecuador: "Equador",
  Egypt: "Egito",
  England: "Inglaterra",
  "El-Salvador": "El Salvador",
  "Equatorial-Guinea": "Guiné Equatorial",
  Eritrea: "Eritreia",
  Estonia: "Estônia",
  Eswatini: "Essuatíni",
  Ethiopia: "Etiópia",
  Fiji: "Fiji",
  Finland: "Finlândia",
  France: "França",
  Gabon: "Gabão",
  Gambia: "Gâmbia",
  Georgia: "Geórgia",
  Germany: "Alemanha",
  Ghana: "Gana",
  Greece: "Grécia",
  Grenada: "Granada",
  Guatemala: "Guatemala",
  Guinea: "Guiné",
  "Guinea-Bissau": "Guiné-Bissau",
  Guyana: "Guiana",
  Haiti: "Haiti",
  Honduras: "Honduras",
  Hungary: "Hungria",
  Iceland: "Islândia",
  India: "Índia",
  Indonesia: "Indonésia",
  Iran: "Irã",
  Iraq: "Iraque",
  Ireland: "Irlanda",
  Israel: "Israel",
  Italy: "Itália",
  Jamaica: "Jamaica",
  Japan: "Japão",
  Jordan: "Jordânia",
  Kazakhstan: "Cazaquistão",
  Kenya: "Quênia",
  Kiribati: "Quiribati",
  "Korea-North": "Coreia do Norte",
  "Korea-South": "Coreia do Sul",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  Kyrgyzstan: "Quirguistão",
  Laos: "Laos",
  Latvia: "Letônia",
  Lebanon: "Líbano",
  Lesotho: "Lesoto",
  Liberia: "Libéria",
  Libya: "Líbia",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lituânia",
  Luxembourg: "Luxemburgo",
  Madagascar: "Madagáscar",
  Malawi: "Malawi",
  Malaysia: "Malásia",
  Maldives: "Maldivas",
  Mali: "Mali",
  Malta: "Malta",
  "Marshall-Islands": "Ilhas Marshall",
  Mauritania: "Mauritânia",
  Mauritius: "Maurício",
  Mexico: "México",
  Micronesia: "Micronésia",
  Moldova: "Moldova",
  Monaco: "Mônaco",
  Mongolia: "Mongólia",
  Montenegro: "Montenegro",
  Morocco: "Marrocos",
  Mozambique: "Moçambique",
  Myanmar: "Mianmar",
  Namibia: "Namíbia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Netherlands: "Países Baixos",
  "New-Zealand": "Nova Zelândia",
  Nicaragua: "Nicarágua",
  Niger: "Níger",
  Nigeria: "Nigéria",
  "North-Macedonia": "Macedônia do Norte",
  Norway: "Noruega",
  Oman: "Omã",
  Pakistan: "Paquistão",
  Palau: "Palau",
  Panama: "Panamá",
  "Papua-New-Guinea": "Papua-Nova Guiné",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Philippines: "Filipinas",
  Poland: "Polônia",
  Portugal: "Portugal",
  Qatar: "Catar",
  Romania: "Romênia",
  Russia: "Rússia",
  Rwanda: "Ruanda",
  "Saint-Kitts-and-Nevis": "São Cristóvão e Nevis",
  "Saint-Lucia": "Santa Lúcia",
  "Saint-Vincent-and-the-Grenadines": "São Vicente e Granadinas",
  Samoa: "Samoa",
  San_Marino: "San Marino",
  Sao_Tome_and_Principe: "São Tomé e Príncipe",
  "Saudi-Arabia": "Arábia Saudita",
  Scotland: "Escócia",
  Senegal: "Senegal",
  Serbia: "Sérvia",
  Seychelles: "Seicheles",
  Sierra_Leone: "Serra Leoa",
  Singapore: "Singapura",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovênia",
  Solomon_Islands: "Ilhas Salomão",
  Somalia: "Somália",
  South_Africa: "África do Sul",
  South_Sudan: "Sudão do Sul",
  Spain: "Espanha",
  Sri_Lanka: "Sri Lanka",
  Sudan: "Sudão",
  Suriname: "Suriname",
  Sweden: "Suécia",
  Switzerland: "Suíça",
  Syria: "Síria",
  Taiwan: "Taiwan",
  Tajikistan: "Tajiquistão",
  Tanzania: "Tanzânia",
  Thailand: "Tailândia",
  Togo: "Togo",
  Tonga: "Tonga",
  Trinidad_and_Tobago: "Trinidad e Tobago",
  Tunisia: "Tunísia",
  Turkey: "Turquia",
  Turkmenistan: "Turcomenistão",
  Tuvalu: "Tuvalu",
  Uganda: "Uganda",
  Ukraine: "Ucrânia",
  "United-Arab-Emirates": "Emirados Árabes Unidos",
  "United-Kingdom": "Reino Unido",
  USA: "Estados Unidos",
  Uruguay: "Uruguai",
  Uzbekistan: "Uzbequistão",
  Vanuatu: "Vanuatu",
  Vatican_City: "Vaticano",
  Venezuela: "Venezuela",
  Vietnam: "Vietnã",
  Yemen: "Iémen",
  Zambia: "Zâmbia",
  Zimbabwe: "Zimbábue",
  World: "Mundo",
};

const countryCodes = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Andorra: "AD",
  Angola: "AO",
  "Antigua-and-Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bhutan: "BT",
  Bolivia: "BO",
  Bosnia_and_Herzegovina: "BA",
  Botswana: "BW",
  Brazil: "BR",
  Brunei: "BN",
  Bulgaria: "BG",
  Burkina_Faso: "BF",
  Burundi: "BI",
  Cabo_Verde: "CV",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  Central_African_Republic: "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  Comoros: "KM",
  Congo: "CG",
  Costa_Rica: "CR",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  Czech_Republic: "CZ",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican-Republic": "DO",
  East_Timor: "TL",
  Ecuador: "EC",
  Egypt: "EG",
  El_Salvador: "SV",
  Equatorial_Guinea: "GQ",
  England: "UK",
  Eritrea: "ER",
  Estonia: "EE",
  Eswatini: "SZ",
  Ethiopia: "ET",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Grenada: "GD",
  Guatemala: "GT",
  Guinea: "GN",
  Guinea_Bissau: "GW",
  Guyana: "GY",
  Haiti: "HT",
  Honduras: "HN",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KI",
  Korea_North: "KP",
  Korea_South: "KR",
  Kosovo: "XK",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  Marshall_Islands: "MH",
  Mauritania: "MR",
  Mauritius: "MU",
  Mexico: "MX",
  Micronesia: "FM",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  New_Zealand: "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  North_Macedonia: "MK",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  Panama: "PA",
  Papua_New_Guinea: "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  Qatar: "QA",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  Saint_Kitts_and_Nevis: "KN",
  Saint_Lucia: "LC",
  Saint_Vincent_and_the_Grenadines: "VC",
  Samoa: "WS",
  San_Marino: "SM",
  Sao_Tome_and_Principe: "ST",
  "Saudi-Arabia": "SA",
  Scotland: "Sld",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  Sierra_Leone: "SL",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  Solomon_Islands: "SB",
  Somalia: "SO",
  South_Africa: "ZA",
  South_Sudan: "SS",
  Spain: "ES",
  Sri_Lanka: "LK",
  Sudan: "SD",
  Suriname: "SR",
  Sweden: "SE",
  Switzerland: "CH",
  Syria: "SY",
  Taiwan: "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  Togo: "TG",
  Tonga: "TO",
  Trinidad_and_Tobago: "TT",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  Tuvalu: "TV",
  Uganda: "UG",
  Ukraine: "UA",
  United_Arab_Emirates: "AE",
  United_Kingdom: "GB",
  USA: "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  Vatican_City: "VA",
  Venezuela: "VE",
  Vietnam: "VN",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  World: "GLOBAL",
};

const CompeticoesPorPaisComponent = ({ jogosPorPais }) => {
  const [expandedCountries, setExpandedCountries] = useState({});

  const toggleExpand = (pais) => {
    setExpandedCountries((prevState) => ({
      ...prevState,
      [pais]: !prevState[pais],
    }));
  };

  const sortedCountries = Object.keys(jogosPorPais).sort((a, b) => {
    const nameA = countryNames[a] || a;
    const nameB = countryNames[b] || b;
    return nameA.localeCompare(nameB);
  });

  return (
    <View style={styles.container}>
      <FlatList
        data={sortedCountries}
        keyExtractor={(item) => item}
        renderItem={({ item: pais }) => {
          const competicoes = jogosPorPais[pais];
          const isExpanded = expandedCountries[pais];
          const translatedName = countryNames[pais] || pais;
          const flagCode = countryCodes[pais] || "UN"; // Usa um código padrão para bandeiras não disponíveis

          return (
            <View style={styles.paisContainer}>
              <TouchableOpacity onPress={() => toggleExpand(pais)}>
                <View style={styles.paisHeader}>
                  <Flag code={flagCode} size={32} />
                  <Text style={styles.paisTitulo}>{translatedName}</Text>
                </View>
              </TouchableOpacity>
              {isExpanded &&
                competicoes.map((competicao, index) => (
                  <CompeticaoCardComponent
                    key={index}
                    imagem={competicao.imagem}
                    nome={competicao.nome}
                    quantidadeJogos={competicao.jogos.length}
                    jogos={competicao.jogos}
                  />
                ))}
            </View>
          );
        }}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    width: "100%",
  },
  paisContainer: {
    marginBottom: 10,
    width: "100%",
    borderWidth: 0.5,
    borderColor: "#2f9fa6",
    borderRadius: 8,
    padding: 10,
    backgroundColor: "#2C2C2E",
  },
  paisHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  paisTitulo: {
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: 10,
    color: "#fff",
  },
});

export default CompeticoesPorPaisComponent;
